version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: main
  labels:
  - automerge
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: vimeo/psalm
    versions:
    - 4.7.0
  - dependency-name: symfony/polyfill-intl-grapheme
    versions:
    - 1.22.1
  - dependency-name: symfony/polyfill-php80
    versions:
    - 1.22.1
  - dependency-name: symfony/polyfill-ctype
    versions:
    - 1.22.1
  - dependency-name: symfony/polyfill-php73
    versions:
    - 1.22.1
  - dependency-name: symfony/polyfill-intl-normalizer
    versions:
    - 1.22.1
  - dependency-name: symfony/string
    versions:
    - 5.2.3
